// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgetkakvkywcgpiovglp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhnZXRrYWt2a3l3Y2dwaW92Z2xwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYwNzc0NjcsImV4cCI6MjA4MTY1MzQ2N30.UtQ2HCBZ2zPvUMKESYeyAZ_8Mxf5OmsPkg35UVkSIPs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});